catalog/urls.py
from django.urls import path
from . import views

app_name = "catalog"
urlpatterns = [
    path("", views.main, name="main"),
    path("<slug:flexiapp_name>/", views.detail, name="detail"),
]

forward/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.forward, name="start"),
]

simple_menu/urls.py
from django.urls import path
from . import views

app_name = "simple_menu"
urlpatterns = [
    path("", views.start, name="main"),
    path("redirect/", views.redirect, name="redirect"),
]

voicemail/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.start, name="start"),
    path("goodbye/", views.say_goodbye, name="say_goodbye"),
    path("send/", views.send, name="send"),
]

catalog/forms.py
from django import forms
from itertools import chain

PHONE_VALIDATION_PATTERN = r"^\d{11}$"


class CallTreatmentForm(forms.Form):
    reason = forms.ChoiceField(
        label="Reject reason",
        widget=forms.Select(attrs={"class": "form-control"}),
        help_text="Enter the reason for rejecting a call.",
        choices=(
            ("busy", "Busy"),
            ("busy-here", "Busy here"),
            ("decline", "Decline"),
            ("does-not-exist", "Does not exist"),
            ("forbidden", "Forbidden"),
            ("rejected", "Rejected"),
            ("not-found", "Not found"),
            ("redirect", "Redirect"),
        ),
        initial="rejected",
        required=False,
    )
    text_or_audio = forms.CharField(
        label="Text or URL to answer",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        help_text="Enter the string to say, or the URL to play.",
        required=False,
    )


class ConcurrentCallsForm(forms.Form):
    phone_number = forms.CharField(
        label="Phone number",
        widget=forms.TextInput(
            attrs={
                "class": "form-control js-multipliable-field",
                "pattern": PHONE_VALIDATION_PATTERN,
                "placeholder": "1XXXXXXXXXX",
                "data-max-entries": "5",
            }
        ),
        help_text="Enter a phone number to dial",
    )


class ForwardForm(forms.Form):
    phone_number = forms.CharField(
        label="Phone number",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "pattern": PHONE_VALIDATION_PATTERN,
                "placeholder": "1XXXXXXXXXX",
            }
        ),
        help_text="Enter a phone number that calls will be forwarded to",
    )
    action = forms.URLField(
        label="URL",
        widget=forms.URLInput(attrs={"class": "form-control"}),
        help_text="Enter a URL containing further FlexML instructions if the call fails",
        required=False,
    )

    hangupOnStar = forms.ChoiceField(
        label="Call ends when * is pressed",
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=(("true", "Yes"), ("false", "No")),
        required=False,
    )


class SimpleMenuForm(forms.Form):
    instructions = forms.CharField(
        label="Instructions",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        help_text="Enter the message callers will hear",
        initial="Thank you for calling. Please press 0 for customer service.",
    )

    def __init__(self, *args, **kwargs):
        super(SimpleMenuForm, self).__init__(*args, **kwargs)
        for idx in chain(range(0, 10), ("*", "#")):
            self.fields[f"url_{idx}"] = forms.URLField(
                label=f'URL for key "{idx}"',
                widget=forms.TextInput(attrs={"class": "form-control"}),
                required=False,
            )


class VoicemailForm(forms.Form):
    greeting_message = forms.CharField(
        label="Greeting message",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        help_text="Enter the message callers will hear before the recording starts",
        initial="Hello. Please leave a message after the beep.",
    )
    goodbye_message = forms.CharField(
        label="Goodbye message",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        help_text="Enter the message callers will hear after the recording ends",
        initial="Thank you for leaving a message.",
    )

    voice_type = forms.ChoiceField(
        label="Voice type",
        widget=forms.Select(attrs={"class": "form-control"}),
        help_text="Select a voice type. The default is male",
        choices=(("man", "Male"), ("woman", "Female")),
    )

    email = forms.EmailField(
        label="Email that will receive voice recording",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "example@somemailservice.com",
            }
        ),
        help_text="This email address will receive a link to the recording",
    )

    containerSid = forms.CharField(
        label="Storage container secure ID",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                "pattern": r"\w{8}-\w{4}-\w{4}-\w{4}-\w{12}",
            }
        ),
        help_text="Find your container SIDs through the CarrierX Portal",
        required=True,
    )

    fileFormat = forms.ChoiceField(
        label="File format",
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=(("wav", "WAV"), ("mp3", "MP3"), ("ul", "UL")),
        help_text="Select the file format for recordings. The default is WAV",
        required=False,
    )

    finishOnKey = forms.CharField(
        label="DTMF key to end recording",
        widget=forms.TextInput(
            attrs={"class": "form-control", "pattern": r"[\d#*]{1,12}|none"}
        ),
        help_text="Enter the DTMF key callers will press to end the recording. "
        "Values accepted in this field are: 0 , 1,2,3,4,5,6,7,8,9,#, "
        "and *. By default, pressing any valid key will end the recording. "
        'The string value "none" can be passed to disable this feature. '
        "Note that multiple values can be passed into a single string. "
        'For example, if the string "123" is passed, then pressing 1 , 2 , '
        "or 3 will end the recording",
        required=False,
    )

    playBeep = forms.ChoiceField(
        label="Play beep",
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=(("true", "Yes"), ("false", "No")),
        help_text="Select whether or not a beep will be played to indicate that a recording "
        "has started. The default is True, and a beep will play",
        required=False,
    )


class SimpleMessageForm(forms.Form):
    text_or_audio = forms.CharField(
        label="Message or URL containing audio file",
        widget=forms.TextInput(
            attrs={
                "class": "form-control js-multipliable-field",
                "data-max-entries": "10",
            }
        ),
        help_text="Enter a message or an audio file URL",
    )

    voice_type = forms.ChoiceField(
        label="Voice type",
        widget=forms.Select(attrs={"class": "form-control"}),
        help_text="Select a voice type. The default is male",
        choices=(("man", "Male"), ("woman", "Female")),
    )

    notify_on_key = forms.CharField(
        label="DTMF key to send notifications",
        widget=forms.TextInput(
            attrs={"class": "form-control", "pattern": r"[\d#*]{1,12}|none"}
        ),
        help_text="If specified, the email address specified below will be "
        "notified if one of the DTMF keys is entered.  This may be used "
        "to gather confirmation or opt-out information from users.",
        required=False,
    )
    notify_email = forms.EmailField(
        label="Email that will receive notifications",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "example@somemailservice.com",
            }
        ),
        help_text="This email address will receive notifications",
        required=False,
    )
    notify_text_or_audio = forms.CharField(
        label="Message or URL containing audio file to be played after notify",
        widget=forms.TextInput(
            attrs={
                "class": "form-control js-multipliable-field",
                "data-max-entries": "10",
            }
        ),
        help_text="Enter a message or an audio file URL",
    )

call_treatment/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
import re

DIAL_PARAMETERS = ("reason", "text_or_audio")


@csrf_exempt
def call_treatment(request):
    text_or_audio = (
        {
            "value": request.GET.get("text_or_audio"),
            "is_url": re.match(r"^https?://", request.GET.get("text_or_audio")),
        }
        if request.GET.get("text_or_audio")
        else None
    )

    if (
        text_or_audio
        and not text_or_audio["is_url"]
        and any(x in text_or_audio["value"] for x in ["{{to}}", "{{ to }}"])
    ):
        template = " ".join(request.GET.get("To", "10000000000"))
        text_or_audio["value"] = text_or_audio["value"].replace("{{to}}", template)
        text_or_audio["value"] = text_or_audio["value"].replace("{{ to }}", template)

    reason = request.GET.get("reason")
    data = {"reason": reason, "text_or_audio": text_or_audio}
    return render(request, "call_treatment.flexml", data)

catalog/views.py
from django.shortcuts import render
from django.http import Http404
from . import forms

FLEXIAPP_NAMES = (
    "simple_message",
    "simple_menu",
    "concurrent_calls",
    "voicemail",
    "forward",
    "call_treatment",
)


def snake_to_upper_camel_case(input_string: str) -> str:
    return "".join(str.capitalize(token) for token in input_string.split("_"))


def snake_to_natural_capitalized(input_string: str) -> str:
    return " ".join(str.capitalize(token) for token in input_string.split("_"))


def main(request):
    return render(request, "home.html")


def detail(request, flexiapp_name):
    if flexiapp_name in FLEXIAPP_NAMES:
        return render(
            request,
            f"{flexiapp_name}.html",
            {
                "flexiapp_name": flexiapp_name,
                "natural_flexiapp_name": snake_to_natural_capitalized(flexiapp_name),
                "form": getattr(
                    forms, snake_to_upper_camel_case(flexiapp_name) + "Form"
                )(),
            },
        )
    raise Http404("The page does not exist")

concurrent_calls/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

DIAL_PARAMETERS = ("action", "method", "timeout", "timeLimit", "hangupOnStar")


@csrf_exempt
def concurrent_calls(request):
    attrs = {
        key: request.GET.get(key)
        for key, value in request.GET.items()
        if key in DIAL_PARAMETERS and value
    }
    data = {"dial_attrs": attrs, "phone_numbers": request.GET.getlist("phone_number")}
    return render(request, "concurrent_calls.flexml", data)

forward/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

DIAL_PARAMETERS = ("action", "method", "timeout", "timeLimit", "hangupOnStar")


@csrf_exempt
def forward(request):
    attrs = {
        key: request.GET.get(key)
        for key, value in request.GET.items()
        if key in DIAL_PARAMETERS and value
    }
    data = {"attrs": attrs, "phone_number": request.GET.get("phone_number")}
    return render(request, "forward.flexml", data)

simple_menu/views.py
from django.shortcuts import render
from urllib import parse
from django.views.decorators.csrf import csrf_exempt
import json


@csrf_exempt
def start(request):
    data = {
        "options": parse.urlencode(
            {key[-1]: url for key, url in request.GET.items() if key.startswith("url_")}
        ),
        "instructions": request.GET.get("instructions"),
    }
    return render(request, "simple_menu.flexml", data)


@csrf_exempt
def redirect(request):
    options = {
        key[-1]: url for key, url in request.GET.items() if key.startswith("url_")
    }
    response = json.loads(request.body, encoding="utf-8")
    return render(request, "redirect.flexml", {"url": options[response["Digits"][0]]})

simple_message/views.py
from django.shortcuts import render
import re

from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def simple_message(request):
    items = (
        {"item": item, "is_url": re.match(r"^https?://", item)}
        for item in request.GET.getlist("text_or_audio")
    )
    voice_type = request.GET.get("voice_type")
    return render(
        request, "simple_message.flexml", {"items": items, "voice_type": voice_type}
    )

voicemail/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .utils import send_email
import json

RECORD_PARAMETERS = (
    "action",
    "callbackUrl",
    "containerSid",
    "direction",
    "errorAction",
    "errorMethod",
    "fileFormat",
    "fileMode",
    "fileSid",
    "finishOnKey",
    "integerKey1",
    "integerKey2",
    "maxLength",
    "method",
    "playBeep",
    "timeout",
    "trim",
    "recordSession",
    "stringKey1",
    "stringKey2",
)


@csrf_exempt
def start(request):
    attrs = {
        key: request.GET.get(key)
        for key, value in request.GET.items()
        if key in RECORD_PARAMETERS and value
    }
    data = {
        "record_attrs": attrs,
        "greeting_message": request.GET.get("greeting_message"),
        "goodbye_message": request.GET.get("goodbye_message"),
        "voice_type": request.GET.get("voice_type"),
        "email": request.GET.get("email"),
    }
    return render(request, "voicemail.flexml", data)


@csrf_exempt
def say_goodbye(request):
    data = {
        "message": request.GET.get("message"),
        "voice_type": request.GET.get("voice_type"),
    }
    return render(request, "voicemail_goodbye.flexml", data)


@csrf_exempt
def send(request):
    email_address = request.GET.get("email")
    recording_properties = json.loads(request.body.decode("utf-8"))
    if email_address and recording_properties:
        send_email("voicemail", email_address, recording_properties["RecordingUrl"])
    return HttpResponse(status=204)

catalog/templates/call_treatment.html
{% extends "detail.html" %}
{% block description %}
Reject call or play audio / speak text.
<br />
Add <i>&#123;&#123;to&#125;&#125;</i> placeholder into <b>Text</b> to speak called number.
{% endblock %}

catalog/templates/concurrent_calls.html
{% extends "detail.html" %}
{% block description %}
Dial two to five phone numbers simultaneously. The first person to answer is connected to the caller. If nobody answers, the call is forwarded to another URL for more FlexML instructions.
{% endblock %}

catalog/templates/detail.html
{% extends "home.html" %}
{% block title %}
    {{ natural_flexiapp_name }}
{% endblock %}
{% block content %}
    <nav aria-label="breadcrumb" class="pt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'catalog:main' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ natural_flexiapp_name }}</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md">
            <h3>{{ natural_flexiapp_name|capfirst }}</h3>
            {% block description %}
                {% lorem 3 %}
            {% endblock %}
        </div>
        <div class="col-md">
            <form method="get" action="/api/{{ flexiapp_name }}/">
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.auto_id }}">{{ field.label }}</label>
                        <div class="form-row">
                            {{ field }}
                        </div>
                        <small id="{{ field.name }}Help" class="form-text text-muted">{{ field.help_text }}
                        </small>
                    </div>
                {% endfor %}
                <button class="btn btn-outline-primary mt-3">Generate the URL <i data-feather="link"></i>
                </button>
            </form>
        </div>
    </div>
    <hr>
    <div class="row pb-3">
        <div class="col-md">
            <h3 class="pt-md-3">Active URL</h3>
            <div class="card">
                <div class="card-body">
                    <a id="sample_link"><code>This is where your URL will be displayed.</code></a>
                </div>
            </div>
        </div>
        <div class="col-md">
            <h3 class="pt-md-3">FlexML</h3>
            <div class="card">
                <div class="card-body">
                    <pre lang="xml"><code>This is where your FlexML will be displayed.</code></pre>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col"></div>
    </div>
{% endblock %}
{% block extra_js %}
    <script>
        $("body").on("submit", "form", function (event) {
            event.preventDefault();
            let data = $(this).serialize();
            let resulting_link = $(this).attr("action") + "?" + data;
            $("#sample_link").text(window.location.protocol + '//' + window.location.host + resulting_link).attr("href", resulting_link.replace(/(csrfmiddlewaretoken=).*?(&)/, ''));
            $.get($(this).attr("action"), data, function (responseText) {
                $('code').html(responseText.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"));
            });
        });
        function make_multipliable() {
            let $inputGroup = $(this).parent();
            $inputGroup.parent().addClass("entry");
            $inputGroup.removeClass("form-row").addClass("input-group");
            $(this).after('<div class="input-group-append">' +
                '<button type="button" class="btn btn-outline-secondary btn-add"><i data-feather="plus" /></button>' +
                '</div>');
        }

        $(document).ready(function () {
            $(".js-multipliable-field").each(make_multipliable);
            feather.replace();
        });
    </script>
{% endblock %}

catalog/templates/forward.html
{% extends "detail.html" %}
{% block description %}
Forward a call to another phone number, or URL for more FlexML instructions given that the initial call is not answered or the line is busy.
{% endblock %}

catalog/templates/home.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="Tryport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="https://www.carrierx.com/favicon.ico"/>

    <title>
        {% block title %}
            No-code CarrierX Apps
        {% endblock %}
    </title>
    <style>
        .feather {
            width: 20px;
            height: 20px;
            stroke: currentColor;
            stroke-width: 2;
            stroke-linecap: round;
            stroke-linejoin: round;
            fill: none;
        }
    </style>
</head>
<body class="bg-light">
<div class="container">
    <div class="py-4 text-center">
        <h1 class="text-center">No-code CarrierX Apps</h1>
    </div>
    {% block content %}
    <hr>
        <div class="row">
            <div class="col">
                <p class="lead text-center pt-3">Generate URLs and small portions of code that enable you to easily learn and implement basic voice apps.</p>
                <div class="card-deck py-2">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Concurrent Calls</h5>
                            <p class="card-text">Dial two to five phone numbers simultaneously. The first person to answer is connected to the caller. If nobody answers, the call is forwarded to another URL for more FlexML instructions.</p>
                        </div>
                        <div class="card-footer">
                            <a href="/concurrent_calls" class="card-link float-right">Try</a>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Simple Message</h5>
                            <p class="card-text">Play one or more audio files and/or speak text.</p>
                        </div>
                        <div class="card-footer">
                            <a href="/simple_message" class="card-link float-right">Try</a>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Call treatment</h5>
                            <p class="card-text">Reject call or play audio / speak text.</p>
                        </div>
                        <div class="card-footer">
                            <a href="/call_treatment" class="card-link float-right">Try</a>
                        </div>
                    </div>
                </div>
                <div class="card-deck py-2">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Simple Menu</h5>
                            <p class="card-text">Play a message for the caller, wait for DTMF input, and direct the call to another URL for more FlexML instructions based on their DTMF input.</p>
                        </div>
                        <div class="card-footer">
                            <a href="/simple_menu" class="card-link float-right">Try</a>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Voicemail</h5>
                            <p class="card-text">Ask the caller to leave a voice message. The audio recording of the voice message will then be sent to a specified email address.</p>
                        </div>
                        <div class="card-footer">
                            <a href="/voicemail" class="card-link float-right">Try</a>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Forward</h5>
                            <p class="card-text">Forward a call to another phone number or URL for more FlexML instructions, given that the initial call is not answered or the line is busy.</p>
                        </div>
                        <div class="card-footer">
                            <a href="/forward" class="card-link float-right">Try</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</div>

{% include "js-imports.html" %}
{% block extra_js %}
{% endblock %}
</body>
</html>

catalog/templates/js-imports.html
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
{% load static %}
<script src="{% static "js/dynamic-form-fields.js" %}"></script>
<script src="https://unpkg.com/feather-icons"></script>

catalog/templates/simple_menu.html
{% extends "detail.html" %}
{% block description %}
Play a message for the caller, wait for DTMF input, and direct them to another URL for more FlexML instructions based on their DTMF input.
{% endblock %}

catalog/templates/simple_message.html
{% extends "detail.html" %}
{% block description %}
Play one or more audio files and/or speak text.
{% endblock %}

catalog/templates/voicemail.html
{% extends "detail.html" %}
{% block description %}
Ask the caller to leave a voice message. The audio recording of the voice message will then be sent to a specified email address.
{% endblock %}